name: Laravel CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Setup PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: '8.0'
        extensions: mbstring, pdo_mysql, exif, pcntl
        
    - name: Composer update
      run: composer install
      
    - name: Install dependencies
      run: composer install

    - name: Run tests
 
